include:
  - package:very_good_analysis/analysis_options.yaml
  - package:bloc_lint/recommended.yaml
analyzer:
  errors:
    avoid_positional_boolean_parameters: ignore
    discarded_futures: ignore
    lines_longer_than_80_chars: ignore
    one_member_abstracts: ignore
  exclude:
    - lib/l10n/gen/*
    - build/**
linter:
  rules:
    public_member_api_docs: false
    avoid_catches_without_on_clauses: false

bloc:
  rules:
    avoid_public_fields: false
    prefer_void_public_cubit_methods: false
