name: stickify
description: A Very Good Project created by Very Good CLI.
version: 4.2.0+16
publish_to: none

environment:
  sdk: ^3.12.0
  flutter: ^3.44.1
dependencies:
  barcode_widget: ^2.0.4
  bloc: ^9.2.0
  cloud_firestore: ^6.5.0
  collection: ^1.19.1
  equatable: ^2.0.8
  firebase_auth: ^6.5.2
  firebase_core: ^4.10.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_localizations:
    sdk: flutter
  go_router: ^17.3.0
  hive_ce: ^2.19.3
  hive_ce_flutter: ^2.3.4
  image_picker: ^1.1.0
  infinite_scroll_pagination: ^5.1.1
  intl: ^0.20.2
  package_info_plus: ^10.2.1
  path_provider: ^2.1.5
  pdf: ^3.12.0
  printing: ^5.14.3
  responsive_framework: ^1.5.1
  uuid: ^4.5.3

dev_dependencies:
  bloc_lint: ^0.4.1
  bloc_test: ^10.0.0
  bloc_tools: ^0.1.0-dev.24
  build_runner: ^2.15.0
  flutter_test:
    sdk: flutter
  go_router_builder: ^4.3.0
  hive_ce_generator: ^1.8.2
  mocktail: ^1.0.5
  very_good_analysis: ^10.2.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/
    - assets/fonts/
  fonts:
    - family: Arial
      fonts:
        - asset: assets/fonts/Arial-Regular.ttf
        - asset: assets/fonts/Arial-Bold.ttf
          weight: 700
