import 'package:flutter/material.dart';
import 'package:stickify/app/routing/router.dart';

/// Product Management screen — lists products and provides navigation
/// to the ProductDetailsScreen via a type-safe route call.
///
/// ## Type-Safe Navigation Example
///
/// This screen demonstrates the go_router_builder pattern for navigating to
/// a sub-route with a path parameter:
///
/// ```dart
/// ProductDetailsRoute(id: '123').go(context);
/// ```
///
/// Notice: no string paths. The compiler will catch typos and missing
/// parameters at build time.
class ProductManagementScreen extends StatelessWidget {
  const ProductManagementScreen({super.key});

  @override
  Widget build(BuildContext context) {
    final colorScheme = Theme.of(context).colorScheme;
    final textTheme = Theme.of(context).textTheme;

    // Dummy product data for demonstration purposes.
    const products = [
      (id: 'prod-001', name: 'Industrial Label A4', sku: 'LBL-A4-001'),
      (id: 'prod-002', name: 'Thermal Sticker Roll', sku: 'STK-TH-002'),
      (id: 'prod-003', name: 'Barcode Label Sheet', sku: 'LBL-BC-003'),
    ];

    return Scaffold(
      backgroundColor: colorScheme.surface,
      body: Padding(
        padding: const EdgeInsets.all(24),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Row(
              children: [
                Expanded(
                  child: Text(
                    'Product Management',
                    style: textTheme.displayLarge,
                  ),
                ),
                ElevatedButton.icon(
                  icon: const Icon(Icons.add),
                  label: const Text('Add Product'),
                  onPressed: () {
                    // TODO(you): Navigate to a new product creation route.
                  },
                ),
              ],
            ),
            const SizedBox(height: 8),
            Text(
              'Manage your product catalogue.',
              style: textTheme.bodyMedium?.copyWith(
                color: colorScheme.onSurfaceVariant,
              ),
            ),
            const SizedBox(height: 24),

            // Product list
            Expanded(
              child: ListView.separated(
                itemCount: products.length,
                separatorBuilder: (_, _) => const SizedBox(height: 8),
                itemBuilder: (context, index) {
                  final product = products[index];
                  return Card(
                    child: ListTile(
                      contentPadding: const EdgeInsets.symmetric(
                        horizontal: 20,
                        vertical: 8,
                      ),
                      leading: Container(
                        padding: const EdgeInsets.all(8),
                        decoration: BoxDecoration(
                          color: colorScheme.primaryContainer,
                          borderRadius: BorderRadius.circular(8),
                        ),
                        child: Icon(
                          Icons.inventory_2_outlined,
                          color: colorScheme.onPrimaryContainer,
                        ),
                      ),
                      title: Text(product.name, style: textTheme.titleSmall),
                      subtitle: Text(
                        'SKU: ${product.sku}',
                        style: textTheme.labelMedium?.copyWith(
                          color: colorScheme.onSurfaceVariant,
                        ),
                      ),
                      trailing: TextButton(
                        // ── Type-Safe Navigation ──────────────────────────
                        // ProductDetailsRoute is generated by
                        // go_router_builder.
                        // `.go(context)` navigates to `/products/<id>` and
                        // keeps us within the Products branch of the shell.
                        onPressed: () =>
                            ProductDetailsRoute(id: product.id).go(context),
                        child: const Text('View Details'),
                      ),
                    ),
                  );
                },
              ),
            ),
          ],
        ),
      ),
    );
  }
}
