// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDrLndIn0BmdiLxp4uaPessGEGKy5Pd6Wc',
    appId: '1:218736345851:web:630b90ef83fc5a467ea65e',
    messagingSenderId: '218736345851',
    projectId: 'stickify-akhil-3705',
    authDomain: 'stickify-akhil-3705.firebaseapp.com',
    storageBucket: 'stickify-akhil-3705.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3IhazXZyxv9tYz5Ob5IaSZ2vjhk_YUs0',
    appId: '1:218736345851:android:a4511014e59bdbc97ea65e',
    messagingSenderId: '218736345851',
    projectId: 'stickify-akhil-3705',
    storageBucket: 'stickify-akhil-3705.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBoE0jQT3hUWGSGzo7Hr_PYMahr9R_U2y4',
    appId: '1:218736345851:ios:b2130efa9d2e3a5f7ea65e',
    messagingSenderId: '218736345851',
    projectId: 'stickify-akhil-3705',
    storageBucket: 'stickify-akhil-3705.firebasestorage.app',
    iosBundleId: 'co.inevitablesoftware.stickify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBoE0jQT3hUWGSGzo7Hr_PYMahr9R_U2y4',
    appId: '1:218736345851:ios:c19cdaeb323b780b7ea65e',
    messagingSenderId: '218736345851',
    projectId: 'stickify-akhil-3705',
    storageBucket: 'stickify-akhil-3705.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDrLndIn0BmdiLxp4uaPessGEGKy5Pd6Wc',
    appId: '1:218736345851:web:9dfeab6af0ec00e17ea65e',
    messagingSenderId: '218736345851',
    projectId: 'stickify-akhil-3705',
    authDomain: 'stickify-akhil-3705.firebaseapp.com',
    storageBucket: 'stickify-akhil-3705.firebasestorage.app',
  );

}