import 'dart:typed_data';
import 'package:stickify/domain/domain.dart';

/// Abstract service interface for generating layout PDF bytes.
abstract interface class LabelLayoutEngine {
  /// Builds a PDF document representation for sheet grids containing product label designs
  /// and returns the generated bytes.
  Future<Uint8List> buildPdfBytes({
    required Product product,
    required ProductVariant variant,
    required LabelTemplate template,
    required int quantity,
    required Set<int> disabledSlots,
  });
}
