import 'dart:typed_data';
import 'package:pdf/pdf.dart';
import 'package:stickify/domain/domain.dart';

/// Abstract service interface for generating layout PDF bytes.
abstract interface class LabelLayoutEngine {
  /// Builds a PDF document representation for sheet grids containing product label designs
  /// and returns the generated bytes.
  ///
  /// The optional [coordinateContext] carries all coordinate transformations
  /// for the job. When `null` or [PrintCoordinateContext.identity], the output
  /// is identical to the pre-1A behavior.
  Future<Uint8List> buildPdfBytes({
    required Product product,
    required ProductVariant variant,
    required LabelTemplate template,
    required int quantity,
    required Set<int> disabledSlots,
    bool printFromBottom = false,
    bool reverseSheetOrder = false,
    PdfPageFormat? physicalFormat,
    PrintCoordinateContext? coordinateContext,
    DateTime? manufacturingDate,
  });
}
