// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import 'package:stickify/data/models/hive/hive_adapters.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(CalibrationRuleHiveModelAdapter());
    registerAdapter(CalibrationTargetHiveModelAdapter());
    registerAdapter(ElementBlueprintHiveModelAdapter());
    registerAdapter(IngredientHiveModelAdapter());
    registerAdapter(LabelTemplateHiveModelAdapter());
    registerAdapter(NutritionFactsHiveModelAdapter());
    registerAdapter(OptimizationPreferencesHiveModelAdapter());
    registerAdapter(PaperConfigurationReferenceHiveModelAdapter());
    registerAdapter(PrintJobHiveModelAdapter());
    registerAdapter(PrintStickerTransformHiveModelAdapter());
    registerAdapter(PrinterCalibrationHiveModelAdapter());
    registerAdapter(PrinterCapabilitiesHiveModelAdapter());
    registerAdapter(PrinterIdentityHiveModelAdapter());
    registerAdapter(PrinterProfileHiveModelAdapter());
    registerAdapter(PrinterTrayProfileHiveModelAdapter());
    registerAdapter(ProductHiveModelAdapter());
    registerAdapter(ProductVariantHiveModelAdapter());
    registerAdapter(SheetConfigHiveModelAdapter());
    registerAdapter(StickerConfigHiveModelAdapter());
    registerAdapter(StickerPointHiveModelAdapter());
    registerAdapter(VariantPrintStatsHiveModelAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(CalibrationRuleHiveModelAdapter());
    registerAdapter(CalibrationTargetHiveModelAdapter());
    registerAdapter(ElementBlueprintHiveModelAdapter());
    registerAdapter(IngredientHiveModelAdapter());
    registerAdapter(LabelTemplateHiveModelAdapter());
    registerAdapter(NutritionFactsHiveModelAdapter());
    registerAdapter(OptimizationPreferencesHiveModelAdapter());
    registerAdapter(PaperConfigurationReferenceHiveModelAdapter());
    registerAdapter(PrintJobHiveModelAdapter());
    registerAdapter(PrintStickerTransformHiveModelAdapter());
    registerAdapter(PrinterCalibrationHiveModelAdapter());
    registerAdapter(PrinterCapabilitiesHiveModelAdapter());
    registerAdapter(PrinterIdentityHiveModelAdapter());
    registerAdapter(PrinterProfileHiveModelAdapter());
    registerAdapter(PrinterTrayProfileHiveModelAdapter());
    registerAdapter(ProductHiveModelAdapter());
    registerAdapter(ProductVariantHiveModelAdapter());
    registerAdapter(SheetConfigHiveModelAdapter());
    registerAdapter(StickerConfigHiveModelAdapter());
    registerAdapter(StickerPointHiveModelAdapter());
    registerAdapter(VariantPrintStatsHiveModelAdapter());
  }
}
