// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import 'package:stickify/data/models/hive/hive_adapters.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(ElementBlueprintHiveModelAdapter());
    registerAdapter(IngredientHiveModelAdapter());
    registerAdapter(LabelTemplateHiveModelAdapter());
    registerAdapter(NutritionFactsHiveModelAdapter());
    registerAdapter(PrintJobHiveModelAdapter());
    registerAdapter(ProductHiveModelAdapter());
    registerAdapter(ProductVariantHiveModelAdapter());
    registerAdapter(SheetConfigHiveModelAdapter());
    registerAdapter(StickerConfigHiveModelAdapter());
    registerAdapter(StickerPointHiveModelAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(ElementBlueprintHiveModelAdapter());
    registerAdapter(IngredientHiveModelAdapter());
    registerAdapter(LabelTemplateHiveModelAdapter());
    registerAdapter(NutritionFactsHiveModelAdapter());
    registerAdapter(PrintJobHiveModelAdapter());
    registerAdapter(ProductHiveModelAdapter());
    registerAdapter(ProductVariantHiveModelAdapter());
    registerAdapter(SheetConfigHiveModelAdapter());
    registerAdapter(StickerConfigHiveModelAdapter());
    registerAdapter(StickerPointHiveModelAdapter());
  }
}
